export const Errors = Object.freeze({
  ROUTER_UNKNOWN_SUBJECT: 'DOMAIN_PROJECTOR_ROUTER_UNKNOWN_SUBJECT',
  ROUTER_HANDLER_ERROR: 'DOMAIN_PROJECTOR_ROUTER_HANDLER_ERROR',
  PRECONDITION_REQUIRED: 'DOMAIN_PROJECTOR_PRECONDITION_REQUIRED',
})
